### ISSUE TITLE
Broken data URLs in labs

### ISSUE THREAD

**Issue by umangsh** [microsoft/AI-For-Beginners#115]
https://mslearntensorflowlp.blob.core.windows.net/data/oxpets_images.tar.gz
Resolving mslearntensorflowlp.blob.core.windows.net (mslearntensorflowlp.blob.core.windows.net)... failed: nodename nor servname provided, or not known.
wget: unable to resolve host address ‘mslearntensorflowlp.blob.core.windows.net’

From https://github.com/microsoft/AI-For-Beginners/blob/main/lessons/4-ComputerVision/08-TransferLearning/lab/OxfordPets.ipynb

**Comment by leestott** [comment]
resolved this the data set is the oxford pets data https://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz updated the readme me and notebook
