### ISSUE TITLE
favicon missing

### ISSUE THREAD

**Issue by ahmad1284** [microsoft/AI-For-Beginners#159]
Add the love icon to be consistent with the other for beginner content

**Comment by ahmad1284** [comment]
Add the love icon to be consistent with the other for beginner content

**Comment by gdequeiroz** [comment]
Hi @ahmad1284, Thank you for opening this issue. Can you please expand on what you mean by the favicon is missing?

**Comment by ahmad1284** [comment]
I am using brave browser on ubuntu and I can't see the favicon on the website for this repo.
Here's the screenshot
![ai-for-beginners](https://user-images.githubusercontent.com/83442967/214117456-8064c882-5160-4a7b-99f6-ce02472376e7.png)

**Comment by BethanyJep** [comment]
Hi, 

I've added favicon - refer to: [this commit](https://github.com/microsoft/AI-For-Beginners/commit/34ad1d84ecd2899c32c9ff2ba59c972d5507bdb0)
