### ISSUE TITLE
how-to-run code instruction link is broken

### ISSUE THREAD

**Issue by cutePanda123** [microsoft/AI-For-Beginners#259]
how-to-run code instruction link is broken. the issue can be reproduced by visiting : https://microsoft.github.io/AI-For-Beginners/etc/how-to-run

<img width="645" alt="image" src="https://github.com/microsoft/AI-For-Beginners/assets/26092755/0cf3829d-f690-44e3-a7f1-b156dab7f88c">

**Comment by leestott** [comment]
fixed #362
