### ISSUE TITLE
QA Tasks for: 15 - Lang modeling

### ISSUE THREAD

**Issue by jlooper** [microsoft/AI-For-Beginners#26]
- [ ] Copyedit
- [ ] Check for Links to Learn, add if necessary, ensure they are instrumented
- [ ] Knowledge Checks
- [ ] Challenge
- [ ] Any art? propose if necessary
- [ ] Assignment
- [x] Pre-Quiz
- [x] Post-Quiz

**Comment by jlooper** [comment]
Several TBDs in here, I think we might add notebooks if possible

**Comment by TrieuLe0801** [comment]
Hello there, 
Can you guys give more detail about the tasks?
