### ISSUE TITLE
instruction link for 'for-teachers.md' is broken

### ISSUE THREAD

**Issue by mreraser** [microsoft/AI-For-Beginners#269]
### Hello! The instruction link for 'for-teachers.md' is something wrong. 

<img width="1491" alt="스크린샷 2023-12-02 오후 4 51 23" src="https://github.com/microsoft/AI-For-Beginners/assets/33192762/8357c1f7-cdfc-4229-86f0-881dc4769951">
<img width="1132" alt="스크린샷 2023-12-02 오후 4 52 27" src="https://github.com/microsoft/AI-For-Beginners/assets/33192762/8b833fe1-28d6-4451-8fcb-c6b87ffe60c6">

**Comment by debayangg** [comment]
Went in-depth into this issue, the main error is that on clicking the link for-teachers.md, the data-page is `etc/for-teachers.md` but it should be `AI-For-Beginners/etc/for-teachers.md`.

Overall that seems to be the main problem, why exactly is docsify rendering this wrong is beyond me rn.
Screenshots:
![ssms1](https://github.com/microsoft/AI-For-Beginners/assets/66942246/8f4d6ad7-f384-449d-98e5-e2ac93b4c339)
![ssms2](https://github.com/microsoft/AI-For-Beginners/assets/66942246/574ebe13-b8e0-49c0-8c56-dc2be81016cd)

Notes:
I think it might be related to the css script and the js script versions, https://jhildenbiddle.github.io/docsify-themeable/#/quick-start, someone please try changing the versions and if it fixes this bug

**Comment by mreraser** [comment]
pull request merged! [PR](https://github.com/microsoft/AI-For-Beginners/pull/270#event-13018408731)
so closing the issue. Thank you!
