### ISSUE TITLE
How can i access the course?

### ISSUE THREAD

**Issue by atkerosbo** [microsoft/AI-For-Beginners#289]
Everything i tried , docker, binder, codespaces everything fails.
Any info how i can access the data and the course?

**Comment by hydromelvictor** [comment]
hi brother it's all in the README unless I'm misunderstanding your request.

**Comment by atkerosbo** [comment]
Hello, I thought there was additional excercisez and data, but yea, I can access it from the README 
thanks for clarifying

**Comment by hydromelvictor** [comment]
it was a pleasure, see you soon

**Comment by hydromelvictor** [comment]
@videlalvaro please close this issues, it's resolved

**Comment by 1224-06** [comment]
COMO PARTICIPAR CON CURSO DE INTELIGENCIA ARTIFICIAL PARA PRINCIPIANTES ?

**Comment by 1224-06** [comment]
Soy nuevo no entiendo la plataforma ?

**Comment by Obispo7** [comment]
Soy nuevo no entiendo la plataforma
