### ISSUE TITLE
cannot run "conda env create --name ai4beg" 

### ISSUE THREAD

**Issue by Alopex-Song** [microsoft/AI-For-Beginners#351]
<img width="1337" alt="Screenshot 2024-07-15 at 12 54 21" src="https://github.com/user-attachments/assets/46f6e850-c19b-4165-bb9f-0dee2de6c665">

in order to solve
ResolvePackageNotFound:
  - pytorch::torchdata=0.3.0
  - pytorch::torchtext=0.12.0
  - pytorch::torchvision=0.12.0

I changed my python to version 3.9, 

in order to install  pytorch::torchtext=0.12.0, I chose to install pytorch 1.11.0

but still:
<img width="737" alt="Screenshot 2024-07-15 at 12 57 49" src="https://github.com/user-attachments/assets/63bfdc42-87af-4ea3-95a1-c9ebed9eeb28">

could you please provide more details in "Setup" section??!

**Comment by yalehu** [comment]
same error

**Comment by RobertErskinedev** [comment]
@Alopex-Song it seems  @BethanyJep does not seem to be monitoring the open issues anymore. I opened a similar issue several weeks ago with no response from her.

**Comment by agodde** [comment]
@Alopex-Song @RobertErskinedev 
I went through the hassle of resolving the dependencies one by one. The following modified requirements.txt works for me at the moment:

`gensim==3.8.3
gym==0.23.1
huggingface==0.0.1
imageio==2.16.2
keras==2.11.0
nltk==3.6.6
pandas==1.4.2
pillow==10.3.0
pygame==2.1.2
scikit-image==0.19.2
seaborn==0.11.2
smart-open==5.2.1
tensorboard-data-server==0.6.1
tensorflow-datasets==4.4.0
tensorflow-hub==0.12.0
tensorflow-text==2.11.0
tensorflow==2.11.1
tensorboard==2.11.2
tokenizers==0.15.2
torchinfo==0.0.8
tqdm==4.66.3
transformers==4.38.0
`
After cloning the repo just replace the contents of the file ./.devcontainer/requirements.txt with the above lines, and the `conda env create...` command should work as expected.

Note: I haven't executed any of the code snippets,yet. So I do not know if upgrading the dependencies breaks anything.

**Comment by rookiee1111** [comment]
I get the following error when trying to install the dependencies
LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested pytorch::torchvision =0.12.0*
  - nothing provides requested pytorch::torchtext =0.12.0*
  - nothing provides requested pytorch::torchdata =0.3.0*
  - nothing provides blas * mkl needed by pytorch-1.11.0.arm64-py3.8_0
  Not able to install mkl
any suggestions how to fix this?
